---
- name: Load and commit configuration file
  hosts: vr-vmx
  gather_facts: false
  connection: local
  roles:
    - Juniper.junos
  tasks:
    - name: Load configuration from a local file and commit
      juniper_junos_config:
        load: merge
        format: set
        src: "/home/anton/automatedNetwork/lab-01/configuration/{{ inventory_hostname.split('.')[0] }}.txt"
      register: response
      register: response

    - name: Print the response
      debug:
        var: response
