---
- name: Load and commit eBGP configuration files
  hosts: CORE
  gather_facts: false
  connection: local
  roles:
    - Juniper.junos
  tasks:
    - name: Load configuration from a local file and commit
      juniper_junos_config:
        load: merge
        format: set
        src: "/home/anton/automatedNetwork/lab-01/configuration/{{ inventory_hostname.split('-')[0] }}-eBGP.txt"
      register: response

    - name: Print the response
      debug:
        var: response

