---
- name: collect configuration
  hosts: vr-vmx
  connection: local
  gather_facts: no
  vars:
    ansible_connection: ansible.netcommon.netconf 
  tasks:
    - name: Get configuration
      junipernetworks.junos.junos_facts:
        gather_subset: config
        config_format: json
      register: output

    - name: Display config
      debug:
        var: output

