- hosts: localhost
  gather_facts: false

  tasks:
    - name: Generate configurations for all core nodes
      include_tasks: per-node-eBGP-tasks.yml
      vars:
        core: "{{ item }}"
      loop:
        - core1
        - core2
      loop_control:
        loop_var: item

