---
- name: Manipulate the configuration of Junos devices
  hosts: vr-vmx
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Rollback to the previous config.
      juniper_junos_config:
        config_mode: 'private'
        rollback: 1
      register: response

    - name: Print the config changes.
      debug:
        var: response.diff_lines

