- name: Get specific Junos facts / Config
  hosts: vr-vmx
  connection: local
  gather_facts: no
  collections:
    - juniper.device
  
  tasks:
    - name: Get Junos OS version
      command:
        commands: "show configuration | display set"
      register: junos_facts

    - name: Print facts
      debug:
        var: junos_facts
